
name: CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: AutoDeploy Request
         id: deploy
         uses: fjogeleit/http-request-action@master
         with:
           url: 'http://34.122.123.186:6643/prod2'
           method: 'POST'
           data: '{ "repository": "https://github.com/riccihenrique/Test_deploy.git", "first_time_commands": ["sudo npm install", "pm2 start index.js --name test"], "commands": ["sudo npm install", "pm2 restart test"] }'
       - name: Show Response
         run: echo ${{ steps.deploy.outputs.response }}
