# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: AutoDeploy Request
         id: deploy
         uses: fjogeleit/http-request-action@master
         with:
           url: 'http://34.134.67.3:6643/prod1'
           method: 'POST'
           data: "{\"repository\": \"https://github.com/riccihenrique/Test_deploy.git\",\"first_time_commands\": [\"pm2 start index.js --name oi\"],\"commands\": [\"pm2 restart oi\"]}"
       - name: Show Response
         run: echo ${{ steps.deploy.outputs.response }}
